apps/operacoes/urls.py
from django.urls import path

from .views import *

# from apps.operacoes.views import (
#     receitas_todas, despesas_todas, investimentos_todos, investimentos_rf_todos, investimentos_rv_todos, investimentos_prev_todos,
    
#     nova_receita, nova_receita_recorrente, efetivar_receita, devolver_receita, editar_receita, deletar_receita, receitas_registradas, receitas_efetivadas, receitas_atrasadas, receitas_futuras, 
    
#     despesa_nova, nova_despesa_recorrente, despesas_efetivar, despesas_estornar, editar_despesa, deletar_despesa, despesas_registradas, despesas_efetivadas, despesas_atrasadas, despesas_futuras,

#     novo_investimento_rf, efetivar_investimento_rf, resgatar_renda_fixa, editar_investimento_rf, reativar_investimento_rf,   investimentos_rf_registrados, investimentos_rf_ativos, investimentos_rf_liquidados, deletar_investimento_rf,

#     novo_investimento_rv, efetivar_investimento_rv, resgatar_renda_variavel, editar_investimento_rv, reativar_investimento_rv, investimentos_rv_registrados, investimentos_rv_ativos, investimentos_rv_liquidados,  
    
#     novo_investimento_previdencia, efetivar_investimento_prev, editar_investimento_prev, investimentos_prev_registrados, investimentos_prev_ativos
# )

urlpatterns = [
        path('receitas/index', receitas_todas, name='lista-receitas'),
        path('receitas/registradas/', receitas_registradas, name='lista-receitas-registradas'),
        path('receitas/efetivadas/', receitas_efetivadas, name='lista-receitas-efetivadas'),
        path('receitas/atrasadas/', receitas_atrasadas, name='lista-receitas-atrasadas'),
        path('receitas/futuras', receitas_futuras, name='lista-receitas-futuras'),
        path('receitas/mes-atual/', receitas_do_mes_atual, name='lista-receitas-do-mes-atual'),
        path('receitas/mes-anterior/', receitas_do_mes_anterior, name='lista-receitas-do-mes-anterior'),
        path('receitas/mes-proximo/', receitas_do_mes_proximo, name='lista-receitas-do-mes-proximo'),
        path('receitas/cadastrar/unica', nova_receita, name='receita-cadastrar'),
        path('receitas/cadastrar/recorrente', nova_receita_recorrente, name='receita-cadastrar-recorrente'),
        path('receitas/efetivar/<int:receita_id>', efetivar_receita, name='receita-efetivar'),
        path('receitas/devolver/<int:receita_id>', devolver_receita, name='receita-devolver'),
        path('receitas/editar/<int:receita_id>', editar_receita, name='receita-editar'),
        path('receitas/deletar/<int:receita_id>', deletar_receita, name='receita-deletar'),  
        path('receitas/index/detalhes/<int:receita_id>', receita_detalhada, name='receita-detalhada'),    
        
        path('despesas/index/', despesas_todas, name='lista-despesas'),
        path('despesas/cadastrar', despesa_nova, name='despesa-cadastrar'),
        path('despesas/cadastrar/recorrente', nova_despesa_recorrente, name='despesa-cadastrar-recorrente'),
        path('despesas/registradas/', despesas_registradas, name='lista-despesas-registradas'),
        path('despesas/efetivadas/', despesas_efetivadas, name='lista-despesas-efetivadas'),
        path('despesas/atrasadas/', despesas_atrasadas, name='lista-despesas-atrasadas'),
        path('despesas/futuras/', despesas_futuras, name='lista-despesas-futuras'),
        path('despesas/futuras/mes-atual', despesas_futuras_mes_atual, name='lista-despesas-futuras-mes-atual'),
        path('despesas/mes-atual/', despesas_do_mes_atual, name='lista-despesas-do-mes-atual'),
        path('despesas/mes-anterior/', despesas_do_mes_anterior, name='lista-despesas-do-mes-anterior'),
        path('despesas/mes-proximo/', despesas_do_mes_proximo, name='lista-despesas-do-mes-proximo'),
        path('despesas/efetivar/<int:despesa_id>', despesas_efetivar, name='despesa-efetivar'),
        path('despesas/estornar/<int:despesa_id>', despesas_estornar, name='despesa-estornar'),
        path('despesas/editar/<int:despesa_id>', editar_despesa, name='despesa-editar'),
        path('despesas/deletar/<int:despesa_id>', deletar_despesa, name='despesa-deletar'),
        path('despesas/index/detalhes/<int:despesa_id>', despesa_detalhada, name='despesa-detalhada'), 

        
        path('investimentos/index', investimentos_todos, name='lista-investimentos'),

        path('investimentos/rf/index/', investimentos_rf_todos, name='lista-investimento-rf'),
        path('investimentos/rf/novo/', novo_investimento_rf, name='cadastrar-investimento-rf'),
        path('investimentos/rf/registrados/', investimentos_rf_registrados, name='rf-registrados'),
        path('investimentos/rf/ativos/', investimentos_rf_ativos, name='rf-ativos'),
        path('investimentos/rf/liquidados/', investimentos_rf_liquidados, name='rf-liquidados'),
        path('investimentos/rf/efetivar/<int:investimento_rf_id>', efetivar_investimento_rf, name='rf-efetivar'),
        path('investimentos/rf/resgatar/<int:investimento_rf_id>', resgatar_renda_fixa, name='rf-resgatar'),
        path('investimentos/rf/reativar/<int:investimento_rf_id>', reativar_investimento_rf, name='rf-reativar'),
        path('investimentos/rf/editar/<int:investimento_rf_id>', editar_investimento_rf, name='rf-editar'),
        path('investimentos/rf/deletar/<int:investimento_rf_id>', deletar_investimento_rf, name='rf-deletar'),
        path('investimentos/rf/detalhes/<int:investimento_rf_id>', investimento_rf_detalhado, name='rf-detalhado'),
        
        
        path('investimentos/rv/index/', investimentos_rv_todos, name='lista-investimento-rv'),
        path('investimentos/rv/novo/', novo_investimento_rv, name='cadastrar-investimento-rv'),
        path('investimentos/rv/registrados/', investimentos_rv_registrados, name='rv-registrados'),
        path('investimentos/rv/ativos/', investimentos_rv_ativos, name='rv-ativos'),
        path('investimentos/rv/liquidados/', investimentos_rv_liquidados, name='rv-liquidados'),
        path('investimentos/rv/efetivar/<int:investimento_rv_id>', efetivar_investimento_rv, name='rv-efetivar'),
        path('investimentos/rv/resgatar/<int:investimento_rv_id>', resgatar_renda_variavel, name='rv-resgatar'),
        path('investimentos/rv/reativar/<int:investimento_rv_id>', reativar_investimento_rv, name='rv-reativar'),
        path('investimentos/rv/editar/<int:investimento_rv_id>', editar_investimento_rv, name='rv-editar'),
        path('investimentos/rv/detalhes/<int:investimento_rv_id>', investimento_rv_detalhado, name='rv-detalhado'),

        path('investimentos/prev/index/', investimentos_prev_todos, name='lista-investimento-prev'), 
        path('investimentos/prev/novo/', novo_investimento_previdencia, name='cadastrar-investimento-prev'), 
        path('investimentos/prev/registrados/', investimentos_prev_registrados, name='prev-registrados'),
        path('investimentos/prev/ativos/', investimentos_prev_ativos, name='prev-ativos'),
        path('investimentos/prev/efetivar/<int:investimento_prev_id>', efetivar_investimento_prev, name='prev-efetivar'),
        path('investimentos/prev/editar/<int:investimento_prev_id>', editar_investimento_prev, name='prev-editar'),
        path('investimentos/prev/detalhes/<int:investimento_prev_id>', investimento_prev_detalhado, name='prev-detalhado'),

        path('cartao/despesas/nova', nova_despesa_cartao, name='cartao-nova-despesa'),
        path('cartao/fatura/parcial', gerar_fatura_parcial, name='cartao-fatura-parcial'),
        #path('cartao/fatura/parcial-cartao', fatura_parcial_cartao, name='cartao-fatura-parcial_2'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.configuracoes.urls')),
    path('', include('apps.usuarios.urls')),
    path('', include('apps.operacoes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/operacoes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from datetime import datetime
from apps.configuracoes.models import Conta, CategoriaReceita, CorretoraInvestimento, ContaPrevidenciaPrivada, CategoriaDespesa, CartaoCredito

class Receita(models.Model):

    OPCOES= [("Sim", "Sim"), ("Não", "Não"),]
    OPCOES_STATUS= [("Registrado", "Registrado"), ("Efetivado", "Efetivado"),]

    data = models.DateTimeField(default=timezone.now, blank=False)
    valor = models.DecimalField(blank=False, null=False, default=0.00, max_digits=10, decimal_places=2)
    credito_ja_realizado = models.CharField(max_length=3, choices=OPCOES)
    descricao = models.CharField(max_length=200, null=False, blank=False)
    categoria = models.ForeignKey(CategoriaReceita, on_delete=models.DO_NOTHING, blank=False, null=False)
    conta_credito = models.ForeignKey(Conta, on_delete=models.DO_NOTHING, blank=False, null=False)

    receita_status = models.CharField(max_length=10, choices=OPCOES_STATUS, default='Registrado')
    data_registro = models.DateTimeField(default=timezone.now, blank=False)
    proprietario = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, default=1)
    
    def __str__(self):
        return self.descricao

class Despesa(models.Model):

    OPCOES= [("Sim", "Sim"), ("Não", "Não"),]
    OPCOES_STATUS= [("Registrado", "Registrado"), ("Efetivado", "Efetivado"),]

    data = models.DateTimeField(default=timezone.now, blank=False)
    valor = models.DecimalField(blank=False, null=False, default=0.00, max_digits=10, decimal_places=2)
    debito_ja_realizado = models.CharField(max_length=3, choices=OPCOES)
    descricao = models.CharField(max_length=200, null=False, blank=False)
    categoria = models.ForeignKey(CategoriaDespesa, on_delete=models.SET_NULL, blank=False, null=True)
    conta_debito = models.ForeignKey(Conta, on_delete=models.SET_NULL, blank=False, null=True)

    despesa_status = models.CharField(max_length=10, choices=OPCOES_STATUS, default='Registrado')
    data_registro = models.DateTimeField(default=timezone.now, blank=False)
    proprietario = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, blank=False, null=True)
    
    def __str__(self):
        return self.descricao

class InvestimentoRendaFixa(models.Model):

    OPCOES= [("Sim", "Sim"), ("Não", "Não"),]
    OPCOES_STATUS= [("Registrado", "Registrado"), ("Ativo", "Ativo"), ("Liquidado", "Liquidado"),]
    OPCOES_INVESTIMENTO = [("CDB", "CDB"), ("CRI", "CRI"), ("CRA", "CRA"), ("DEBENTURE", "DEBENTURE"), ("Fundo de RF", "Fundo de RF"), ("LCA", "LCA"), ("LCI", "LCI"), ("POUPANÇA", "POUPANÇA"),("TESOURO", "TESOURO"), ("Outros", "Outros"),]
    OPCOES_RENTABILIDADE = [("PÓS-FIXADA", "PÓS-FIXADA"), ("PRÉ-FIXADA", "PRÉ-FIXADA"),]

    data_investimento = models.DateTimeField(default=timezone.now, blank=False)
    data_vencimento = models.DateTimeField(default=timezone.now, blank=False)
    tipo_investimento_rf = models.CharField(max_length=12, choices=OPCOES_INVESTIMENTO)
    tipo_rentabilidade = models.CharField(max_length=11, choices=OPCOES_RENTABILIDADE)
    corretora = models.ForeignKey(CorretoraInvestimento, on_delete=models.DO_NOTHING, blank=False, null=False)
    valor_investido = models.DecimalField(blank=False, null=False, default=0.00, max_digits=10, decimal_places=2)
    taxa_negociada = models.CharField(max_length=200, null=False, blank=False)
    descricao = models.CharField(max_length=200, null=False, blank=False)
    taxas_corretagem_aplicacao = models.DecimalField(blank=False, null=False, default=0.00, max_digits=12, decimal_places=2)
    irpf_aplicacao = models.DecimalField(blank=False, null=False, default=0.00, max_digits=12, decimal_places=2)
    
    conta_debito = models.ForeignKey(Conta, on_delete=models.DO_NOTHING, blank=False, null=False)
    investimento_debitado_em_conta = models.CharField(max_length=3, choices=OPCOES)
    investimento_status = models.CharField(max_length=10, choices=OPCOES_STATUS)
    
    valor_resgate_liquido = models.DecimalField(blank=False, null=False, default=0.00, max_digits=10, decimal_places=2)
    taxas_corretagem_resgate = models.DecimalField(blank=False, null=False, default=0.00, max_digits=12, decimal_places=2)
    irpf_resgate = models.DecimalField(blank=False, null=False, default=0.00, max_digits=10, decimal_places=2)
    data_resgate = models.DateTimeField(default=timezone.now, blank=False)
    
    data_registro = models.DateTimeField(default=timezone.now, blank=False)
    proprietario = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, default=1)

    def __str__(self):
        return self.descricao

class InvestimentoRendaVariavel(models.Model):

    OPCOES= [("Sim", "Sim"), ("Não", "Não"),]
    OPCOES_STATUS= [("Registrado", "Registrado"), ("Ativo", "Ativo"), ("Liquidado", "Liquidado"),]
    OPCOES_INVESTIMENTO = [("Ações", "Ações"), ("CRIPTO", "CRIPTO"), ("FII", "FII"), ("ETFs", "ETFs"), ("Fundo de RV", "Fundo de RV"), ("Outros", "Outros"),]

    data_investimento = models.DateTimeField(default=timezone.now, blank=False)
    tipo_investimento_rv = models.CharField(max_length=12, choices=OPCOES_INVESTIMENTO)
    corretora = models.ForeignKey(CorretoraInvestimento, on_delete=models.DO_NOTHING, blank=False, null=False)
    valor_investido = models.DecimalField(blank=False, null=False, default=0.00, max_digits=12, decimal_places=2)
    valor_resgate_liquido = models.DecimalField(blank=False, null=False, default=0.00, max_digits=10, decimal_places=2)
    quantidade_cotas = models.PositiveIntegerField(blank=False, null=False, default=1)
    preco_medio = models.DecimalField(blank=False, null=False, default=0.00, max_digits=10, decimal_places=2)
    descricao = models.CharField(max_length=200, null=False, blank=False)
    taxas_corretagem_aplicacao = models.DecimalField(blank=False, null=False, default=0.00, max_digits=12, decimal_places=2)
    irpf_aplicacao = models.DecimalField(blank=False, null=False, default=0.00, max_digits=12, decimal_places=2)
    
    conta_debito = models.ForeignKey(Conta, on_delete=models.DO_NOTHING, blank=False, null=False)
    investimento_debitado_em_conta = models.CharField(max_length=3, choices=OPCOES)
    investimento_status = models.CharField(max_length=10, choices=OPCOES_STATUS)
    
    taxas_corretagem_resgate = models.DecimalField(blank=False, null=False, default=0.00, max_digits=12, decimal_places=2)
    irpf_resgate = models.DecimalField(blank=False, null=False, default=0.00, max_digits=12, decimal_places=2)
    data_resgate = models.DateTimeField(default=timezone.now, blank=False)

    data_registro = models.DateTimeField(default=timezone.now, blank=False)
    proprietario = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, default=1)

    def __str__(self):
        return self.descricao

class InvestimentoPrevidenciaPrivada(models.Model):

    OPCOES= [("Sim", "Sim"), ("Não", "Não"),]
    OPCOES_STATUS= [("Registrado", "Registrado"), ("Efetivado", "Efetivado"), ]

    conta_previdencia = models.ForeignKey(ContaPrevidenciaPrivada, on_delete=models.DO_NOTHING, blank=False, null=False)
    descricao = models.CharField(max_length=200, null=False, blank=False)
    valor_investido = models.DecimalField(blank=False, null=False, default=0.00, max_digits=12, decimal_places=2)
    data_investimento = models.DateTimeField(default=timezone.now, blank=False)
    conta_debito = models.ForeignKey(Conta, on_delete=models.DO_NOTHING, blank=False, null=False)
    investimento_debitado_em_conta = models.CharField(max_length=3, choices=OPCOES)
    investimento_status = models.CharField(max_length=10, choices=OPCOES_STATUS)

    data_registro = models.DateTimeField(default=timezone.now, blank=False)
    proprietario = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, default=1)

    def __str__(self):
        return self.descricao

class DespesaCartao(models.Model):

    OPCOES_STATUS= [("Registrada", "Registrada"), ("Paga", "Paga"),]

    data = models.DateField(default=timezone.now, blank=False)
    valor = models.DecimalField(blank=False, null=False, default=0.00, max_digits=10, decimal_places=2)
    numero_parcelas = models.IntegerField(blank=False, null=False, default=1)
    descricao = models.CharField(max_length=200, null=False, blank=False)
    categoria = models.ForeignKey(CategoriaDespesa, on_delete=models.SET_NULL, blank=False, null=True)
    cartao_selecionado = models.ForeignKey(CartaoCredito, on_delete=models.SET_NULL, blank=False, null=True)
    despesa_status = models.CharField(max_length=10, choices=OPCOES_STATUS, default='Registrada')
    data_registro = models.DateTimeField(default=timezone.now, blank=False)
    proprietario = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, blank=False, null=True)
    data_primeira_fatura = models.DateField(default=timezone.now, blank=False)
    
    def __str__(self):
        return self.descricao

class DespesaIndividualizadaCartao(models.Model):

    OPCOES_STATUS= [("Registrada", "Registrada"), ("Paga", "Paga"),]

    data = models.DateField(default=timezone.now, blank=False)
    valor = models.DecimalField(blank=False, null=False, default=0.00, max_digits=10, decimal_places=2)
    qual_parcela = models.IntegerField(blank=False, null=False, default=1)
    total_parcelas = models.IntegerField(blank=False, null=False, default=1)
    descricao = models.CharField(max_length=200, null=False, blank=False)
    categoria = models.ForeignKey(CategoriaDespesa, on_delete=models.SET_NULL, blank=False, null=True)
    despesa_associada = models.ForeignKey(DespesaCartao, on_delete=models.SET_NULL, blank=False, null=True)
    qual_cartao = models.ForeignKey(CartaoCredito, on_delete=models.SET_NULL, blank=False, null=True)
    despesa_status = models.CharField(max_length=10, choices=OPCOES_STATUS, default='Registrada')

templates/operacoes/despesa-editar.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1 class="card-title">Despesas</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                    <li class="breadcrumb-item">Despesas</li>
                    <li class="breadcrumb-item active">Editar Despesa</li>
                </ol> 
            </nav> 
        </div>  
        
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Editar Despesa</h5>
                <form action="{% url 'despesa-editar' despesa_id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %} 
                    <div>
                        {% for field in form_editar_despesa.visible_fields %}
                            <div class="row mb-3">
                                <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{field.label}}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Editar Despesa</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <script src="{% static 'js/jquery-3.7.1.js' %}"></script>
    <script>
        $(document).ready(function(){
            // Adicione um identificador aos campos de data para facilitar a seleção
            var dataDespesaField = $('#id_data');
            var debitoJaRealizadoField = $('#id_debito_ja_realizado');

            dataDesepesaField.change(function(){
                // Obter o valor da data e converter para objetos Date
                var dataDespesa = dataDespesaField.val();
                var dataDespesa = new Date(dataDespesa);

                // Obter a data atual do sistema
                var hoje = new Date();

                // Verificar se a "data" da despesa é posterior a data "hoje"
                if ((dataDespesa > hoje))
                {
                    alert('Você está lançando uma data futura. Se o formulário for enviado assim o sistema salvará automaticamente a Despesa como Débito NÃO Realizado, independente de sua resposta em "Valor Debitado em Conta"');
                }
            });
        });
    </script>
{% endblock %}

templates/operacoes/despesa-nova.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1 class="card-title">Despesas</h1>
            <nav>
                <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                <li class="breadcrumb-item">Despesas</li>
                <li class="breadcrumb-item active">Nova Despesa</li>
                </ol>
            </nav>
        </div> 
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Nova Despesa</h5>
                
                <form id="novaDespesaForm" action="{% url 'despesa-cadastrar' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                        {% for field in form_nova_despesa.visible_fields %}
                            <div class="row mb-3">
                                <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{field.label}}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>

                        {% endfor %}
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Cadastrar Despesa</button>
                            </div>
                        </div>
                </form> 
            </div>
        </div>
    </main>          

    <script src="{% static 'js/jquery-3.7.1.js' %}"></script>
    <script>
        $(document).ready(function(){
            // Adicione um identificador aos campos de data para facilitar a seleção
            var dataDespesaField = $('#id_data');
            var debitoJaRealizadoField = $('#id_debito_ja_realizado');

            dataDespesaField.change(function(){
                // Obter o valor da data e converter para objetos Date
                var dataDespesa = dataDespesaField.val();
                var dataDespesa = new Date(dataDespesa);

                // Obter a data atual do sistema
                var hoje = new Date();

                // Verificar se a "data" da receita é posterior a data "hoje"
                if ((dataDespesa > hoje))
                {
                    alert('Você está lançando uma data futura. A Despesa será cadastrada como Débito NÃO Realizado, independente de sua resposta em "Valor Debitado em Conta"');
                }
            });
        });
    </script>
{% endblock %}

templates/operacoes/invest-rf-editar.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1 class="card-title">Investimentos em Renda Fixa</h1>
            <nav>
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                  <li class="breadcrumb-item">Investimentos</li>
                  <li class="breadcrumb-item">Renda Fixa</li>
                  <li class="breadcrumb-item active">Editar Investimento</li>
                </ol>
            </nav>
        </div> 

        <div class="card">
			<div class="card-body">
				<h5 class="card-title">Editar Investimento em Renda Fixa</h5>
                <form id="investimentoForm" action="{% url 'rf-editar' investimento_rf_id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %} 
                        {% for field in form_editar_investimento.visible_fields %}
                        <div class="row mb-3">
                            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{field.label}}</label>
                            <div class="col-sm-10">{{ field }}</div>
                        </div>
                    {% endfor %}
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Editar Investimento</button>
                            </div>
                        </div>
                </form>
            </div>
        </div>
    </main>>

    <script src="{% static 'js/jquery-3.7.1.js' %}"></script>
    <script>
        $(document).ready(function(){
            // Adicione um identificador aos campos de data para facilitar a seleção
            var dataInvestimentoField = $('#id_data_investimento');
            var dataVencimentoField = $('#id_data_vencimento');

            // Adicione um manipulador de eventos ao campo de data de vencimento
            dataVencimentoField.change(function(){
                // Obter valores das datas
                var dataInvestimento = dataInvestimentoField.val();
                var dataVencimento = dataVencimentoField.val();

                // Converter para objetos Date
                var dateInvestimento = new Date(dataInvestimento);
                var dateVencimento = new Date(dataVencimento);

                // Verificar se data_vencimento é após data_investimento
                if (dateVencimento <= dateInvestimento) {
                    alert('A data de vencimento deve ser posterior à data de investimento.');
                    // Você pode adicionar outras ações aqui, como limpar o campo ou mostrar uma mensagem na interface.
                }
            });

            // Mantenha o código anterior para a verificação no clique do botão, caso o usuário tente enviar sem selecionar a segunda data
            $('#submitButton').click(function(event){
                // Evitar envio padrão do formulário
                event.preventDefault();

                // Obter valores das datas
                var dataInvestimento = dataInvestimentoField.val();
                var dataVencimento = dataVencimentoField.val();

                // Converter para objetos Date
                var dateInvestimento = new Date(dataInvestimento);
                var dateVencimento = new Date(dataVencimento);

                // Verificar se data_vencimento é após data_investimento
                if (dateVencimento <= dateInvestimento) {
                    alert('A data de vencimento deve ser posterior à data de investimento.');
                    // Ou você pode adicionar uma mensagem de erro no HTML ou fazer qualquer outra ação desejada.
                } else {
                    // Envie o formulário se a validação passar
                    $('#investimentoForm').submit();
                }
            });
        });
    </script>
{% endblock %}

templates/operacoes/renda-fixa-resgatar.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1 class="card-title">Investimentos em Renda Fixa</h1>
            <nav>
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                  <li class="breadcrumb-item">Investimentos</li>
                  <li class="breadcrumb-item">Renda Fixa</li>
                  <li class="breadcrumb-item active">Resgatar Investimento</li>
                </ol>
            </nav>
        </div> 

        <div class="card">
			<div class="card-body">
				<h5 class="card-title">Resgatar Investimento em Renda Fixa</h5>
                <form action="{% url 'rf-resgatar' investimento_rf_id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %} 
                    <div>
                        {% for field in form_resgatar_rf.visible_fields %}
                            <div>
                                <label for="{{ field.id_for_label }}" >{{field.label}}</label>
                                {{ field }}<br>
                            </div>
                        {% endfor %}
                    </div>
                    <div>
                        <br>
                        <button type="submit">Resgatar Renda Fixa</button>
                    </div>
                </form>
            </div>
        </div>
    </main>>
{% endblock %}